// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: d38df3bfbf
// Version Date: Sun Apr 22 05:12:28 UTC 2018

package main

import (
	"flag"

	// This Service
	"github.com/lvtiendev/truss_example/echo-service/svc/server"
	"github.com/lvtiendev/truss_example/echo-service/svc/server/cli"
)

func main() {
	// Update addresses if they have been overwritten by flags
	flag.Parse()

	server.Run(cli.Config)
}
