// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: d38df3bfbf
// Version Date: Sun Apr 22 05:12:28 UTC 2018

package handlers

import (
	pb "github.com/lvtiendev/truss_example"
)

// Echo implements Service.
func Echo(InEcho string) (*pb.EchoRequest, error) {
	request := pb.EchoRequest{
		In: InEcho,
	}
	return &request, nil
}

// Louder implements Service.
func Louder(InLouder string, LoudnessLouder int32) (*pb.LouderRequest, error) {
	request := pb.LouderRequest{
		In:       InLouder,
		Loudness: LoudnessLouder,
	}
	return &request, nil
}

// LouderGet implements Service.
func LouderGet(InLouderGet string, LoudnessLouderGet int32) (*pb.LouderRequest, error) {
	request := pb.LouderRequest{
		In:       InLouderGet,
		Loudness: LoudnessLouderGet,
	}
	return &request, nil
}
